### ISSUE TITLE
Button presses not showing

### ISSUE THREAD

**Issue by BarbieBarbsson** [thomasloven/hass-plejd#92]
The event for button pressed doesn't seem to be updating. It only triggers once upon restart then nothing. I couldn't find any errors. Please let me know if I'm missing something.

**Comment by durrav** [comment]
Button presses works for me, but the scenarios aren’t running in HA when triggered from a button. If they are triggered from the Plejd-app they work.

**Comment by thomasloven** [comment]
> Button presses works for me

I'm guessing you have a wireless WPH button?

It should now work for every button after a reboot in Version 0.14.3

**Comment by durrav** [comment]
> > Button presses works for me
> 
> I'm guessing you have a wireless WPH button?
> 
> It should now work for every button after a reboot in Version 0.14.3

I don’t have any scenarios attached to my WPH, but the button events from my WPH does work. 
I have scenarios for double clicks that I am triggering automations in HA with. Will test 0.14.3.

**Comment by BarbieBarbsson** [comment]
I only have normal switches atm but now with the latest update everything seems to be working. Great work :)

**Comment by durrav** [comment]
Scenarios are still not running in HA when triggered from a button in 0.14.3.

**Comment by andrelindstrom** [comment]
I have the same problem. I use the double-click senario to toggle lights. Works fine when senarios is triggered from the plejd app but no respond from buttons to HA.

**Comment by durrav** [comment]
> I have the same problem. I use the double-click senario to toggle lights. Works fine when senarios is triggered from the plejd app but no respond from buttons to HA.

I resolved it with a Node-Red flow that counts the amount of presses.

[{"id":"1c3de16b3ed74c6f","type":"change","z":"6dac349694b969cb","name":"Reset","rules":[{"t":"set","p":"reset","pt":"msg","to":"foo","tot":"str"},{"t":"delete","p":"payload","pt":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":450,"y":180,"wires":[["f799aedf03dba501"]]},{"id":"936e3f68e5f6e244","type":"inject","z":"6dac349694b969cb","name":"Reset","props":[{"p":"payload","v":"","vt":"date"},{"p":"topic","v":"","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":"0.5","topic":"","payload":"","payloadType":"date","x":270,"y":220,"wires":[["1c3de16b3ed74c6f"]]},{"id":"9747ee4b827603d1","type":"inject","z":"6dac349694b969cb","name":"Start","repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":273.33331298828125,"y":131.111083984375,"wires":[["f799aedf03dba501","dc7a32473b6c7278"]]},{"id":"f799aedf03dba501","type":"counter","z":"6dac349694b969cb","name":"","init":"0","step":"1","lower":null,"upper":null,"mode":"increment","outputs":"1","x":460,"y":130,"wires":[["9c169cbd9b0c3130","220b469daaa9cc2b"]]},{"id":"672d21f96e54e5c5","type":"switch","z":"6dac349694b969cb","name":"count presses","property":"count","propertyType":"flow","rules":[{"t":"eq","v":"1","vt":"num"},{"t":"eq","v":"2","vt":"num"},{"t":"eq","v":"3","vt":"num"},{"t":"eq","v":"4","vt":"num"}],"checkall":"true","repair":false,"outputs":4,"x":660,"y":240,"wires":[["a8cce5f9e9d5e0c2"],["a8cce5f9e9d5e0c2"],["0458c5ba46cb3f6c"],["0458c5ba46cb3f6c"]],"info":"Just expand the flow.count to how ever many\npresses you want/need."},{"id":"dc7a32473b6c7278","type":"trigger","z":"6dac349694b969cb","name":"","op1":"","op2":"0","op1type":"nul","op2type":"str","duration":"6","extend":false,"units":"s","reset":"","bytopic":"all","outputs":1,"x":280,"y":180,"wires":[["1c3de16b3ed74c6f"]]},{"id":"220b469daaa9cc2b","type":"change","z":"6dac349694b969cb","name":"Flow set","rules":[{"t":"set","p":"count","pt":"flow","to":"count","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":640,"y":90,"wires":[[]]},{"id":"b18eaf107f3a5026","type":"delay","z":"6dac349694b969cb","name":"","pauseType":"delay","timeout":"3","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"outputs":1,"x":640,"y":180,"wires":[["672d21f96e54e5c5"]]},{"id":"9c169cbd9b0c3130","type":"switch","z":"6dac349694b969cb","name":"","property":"count","propertyType":"msg","rules":[{"t":"eq","v":"1","vt":"num"}],"checkall":"true","repair":false,"outputs":1,"x":630,"y":130,"wires":[["b18eaf107f3a5026"]]},{"id":"a8cce5f9e9d5e0c2","type":"change","z":"6dac349694b969cb","name":"Single Press","rules":[{"t":"set","p":"payload","pt":"msg","to":"Single Press","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":850,"y":220,"wires":[[]]},{"id":"0458c5ba46cb3f6c","type":"change","z":"6dac349694b969cb","name":"Double Press","rules":[{"t":"set","p":"payload","pt":"msg","to":"Double Press","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":860,"y":260,"wires":[[]]},{"id":"d68741023c92376b","type":"comment","z":"6dac349694b969cb","name":"DELAY - Readme","info":"The DELAY time has to be a bit longer than how\nlong it takes you to press the button the\nmaximum number of times.\nRead information in the SWITCH node too!","x":660,"y":50,"wires":[]},{"id":"5e00c5867da87602","type":"comment","z":"6dac349694b969cb","name":"Input","info":"","x":270,"y":90,"wires":[]},{"id":"36e6e194f5525e7f","type":"comment","z":"6dac349694b969cb","name":"Outputs","info":"Debug nodes are here now, but just connect\nthem to what ever you want.\nThe messages sent are in the nodes just before\nthe debug nodes.\n","x":830,"y":180,"wires":[]}]

**Comment by igalg99** [comment]
> I have the same problem. I use the double-click senario to toggle lights. Works fine when senarios is triggered from the plejd app but no respond from buttons to HA.

I also have same problem.
I have scenes that I activate on double click. 
The scenes from plejd are created in home assistant as entities with the name "name of the scene" + "activated ( example: "scene one activated "

Up until version 13 when I double click a light to activate a scene it triggers "scene one activated " and I have been using this trigger in home assistant for different automations. 

From version 14 , home assistant event is not recorded on double click. Nothing happens in the entity 'scene one activated"  while the actual scene in the plejd (not in HA) does activate. 

What I noticed that if I go to the scene in the plejd app and press on "run scene" then it does trigger the entity "scene one activated" . 

Do basically it triggers only if I run it via the app but not when I physically double click the switch (although the scene itself does activate but the entity is not triggered)

I hope I made myself clear , I know I repeated the same thing few times. It was intentional :)

**Comment by thomasloven** [comment]
Should be fixed in 0.14.4

**Comment by durrav** [comment]
> Should be fixed in 0.14.4

Yes, scenes does activate using buttons now. Thanks!

**Comment by andrelindstrom** [comment]
> Should be fixed in 0.14.4

Sounds great! :-) Good job with this add on so far! Appreciate it!
